name: GhostLife
version: ${project.version}
main: com.github.sirokuri_.ghostlife.ghostlife
api-version: 1.15
authors: [ghost_46]
description: LIFE plugin
softdepend:
  - Vault

commands:
  ghostlife:
    description: コンフィグリロード
    permission: GhostLifeCommand.permission.Admin
  adddamege:
    description: ダメージセット
    permission: GhostLifeCommand.permission.Admin
  sellmmgui:
    description: MMアイテム売却
    permission: GhostLifeCommand.permission.Member
  smg:
    description: MMアイテム売却
    permission: GhostLifeCommand.permission.Member
  playerskullgive:
    description: playerhead配布
    permission: GhostLifeCommand.permission.Admin

permissions:
  GhostLifeCommand.permission.Admin:
    default: op
  GhostLifeCommand.permission.Member:
    default: true